{
 "title": "statistics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "total messages count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nsq_topic_message_count)" }
   ]
  },
  {
   "title": "total nodes count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(nsq_node_topic_count)" }
   ]
  },
  {
   "title": "total topics count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nsq_topic_message_count) by (topic))"
    }
   ]
  },
  {
   "title": "total clients count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(nsq_channel_client_count)" }
   ]
  },
  {
   "title": "topic-channel depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nsq_channel_depth) by (topic, channel) > 0",
     "legendFormat": "{{topic}} -- {{channel}}"
    }
   ]
  },
  {
   "title": "topic depth count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(nsq_topic_depth) by (topic)"
    }
   ]
  },
  {
   "title": "produce messages ops  peer topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nsq_topic_message_count[5m])) by (topic)",
     "legendFormat": "{{topic}} ops"
    }
   ]
  },
  {
   "title": "node topic",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(nsq_node_topic_count) by (hostname, http_port, remote_address, version)"
    }
   ]
  },
  {
   "title": "topic's channel count",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(nsq_topic_channel_count) by (topic, paused)"
    }
   ]
  }
 ]
}